esphome:
  name: fishtank

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "19081908"

ota:
  password: "19081908"

captive_portal:

web_server:
  port: 80

dallas:
  - pin: GPIO21

# Individual sensors
sensor:
  - platform: dallas
    address: 0x1601145d49c91e28
    name: "Temperatura Acqua"

text_sensor:
  - platform: template
    name: "Ultima pulizia"
    id: last_clean

light:
  - platform: monochromatic
    name: "Luci Dimmer"
    id: lights
    output: ledc_pwm
    on_turn_on:
      - switch.turn_on: switch_lights
    on_turn_off:
      - switch.turn_off: switch_lights

stepper:
  - platform: uln2003
    id: fish_feeder_stepper
    pin_a: GPIO26
    pin_b: GPIO25
    pin_c: GPIO33
    pin_d: GPIO32
    max_speed: 200 steps/s
    sleep_when_done: True

output:
  - platform: ledc
    id: ledc_pwm
    pin: GPIO27

globals:
   # you will need globals for any other alarm times
   - id: lights_timer_slot_hour
     type: int[4]
     restore_value: true
     
   - id: lights_timer_slot_minute
     type: int[4]
     restore_value: true
     
   - id: lights_timer_slot_value_home
     type: int[4]
     restore_value: true

   - id: lights_timer_slot_value_away
     type: int[4]
     restore_value: true

   - id: fishfeeder_timer_slot_hour
     type: int[2]
     restore_value: true
     
   - id: fishfeeder_timer_slot_minute
     type: int[2]
     restore_value: true

   - id: fishfeeder_timer_check
     type: int[2]
     restore_value: true
     initial_value: '{0,0}'

   - id: fishfeeder_position
     type: int
     restore_value: true

packages:
  wifi: !include packages/wifi.yaml
  number: !include packages/number.yaml
  time: !include packages/time.yaml
  binary_sensor: !include packages/binary_sensor.yaml
  switch: !include packages/switch.yaml
  button: !include packages/buttons.yaml
